name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Run tests
    steps:
    - name: Install Swift 5.1
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - uses: actions/checkout@master
    - name: Run tests
      run: swift test
